[package]
name = "geometry-derive"
version = "0.1.0"
authors = ["Adolfo <adolfo@infi.nl>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.99"
quote = "1.0.21"
geometry = { path = "../geometry" }
